### ISSUE TITLE
wxWork报错

### ISSUE THREAD

**Issue by 121qwq** [Merrickk/BncrFiles#7]
[2024-07-08T03:00:14.281] [WARN] BncrJS - > 收到[/api/bot/wxWork]请求~
接收消息模块出错 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at /bncr/BncrData/Adapter/wxWork.js:83:17
    at _0x403a49._0x337088 [as handle_request] (evalmachine.<anonymous>:1:1297478)
    at _0x3629f5 (evalmachine.<anonymous>:1:1302068)
    at _0x48d64d._0x2acc1f [as dispatch] (evalmachine.<anonymous>:1:1301518)
    at _0x403a49._0x337088 [as handle_request] (evalmachine.<anonymous>:1:1297478)
    at evalmachine.<anonymous>:1:1308573
    at Function._0x49730d [as process_params] (evalmachine.<anonymous>:1:1310021)
    at _0x4cfd01 (evalmachine.<anonymous>:1:1308399)
    at xmlbodyparser (/bncr/BncrData/node_modules/express-xml-bodyparser/lib/types/xml.js:68:14)
    at _0x403a49._0x337088 [as handle_request] (evalmachine.<anonymous>:1:1297478)
    at _0xd08667 (evalmachine.<anonymous>:1:1309728)
    at evalmachine.<anonymous>:1:1308605
    at Function._0x49730d [as process_params] (evalmachine.<anonymous>:1:1310021)
    at _0x4cfd01 (evalmachine.<anonymous>:1:1308399)
    at responseHandler (/bncr/BncrData/node_modules/express-xml-bodyparser/lib/types/xml.js:64:9)
    at Parser.<anonymous> (/bncr/BncrData/node_modules/express-xml-bodyparser/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (/bncr/BncrData/node_modules/express-xml-bodyparser/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/bncr/BncrData/node_modules/sax/lib/sax.js:625:35)
    at emitNode (/bncr/BncrData/node_modules/sax/lib/sax.js:630:5)
    at closeTag (/bncr/BncrData/node_modules/sax/lib/sax.js:890:7)
    at SAXParser.write (/bncr/BncrData/node_modules/sax/lib/sax.js:1437:13)
[2024-07-08T03:00:14.837] [WARN] BncrJS - > 收到[/api/bot/wxWork]请求~

**Comment by 121qwq** [comment]
发送消息函数出错 {"errcode":40014,"errmsg":"invalid access_token"}

**Comment by Merrickk** [comment]
看一下是不是有的依赖没装好
